import{a as v,S as O,i}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const $="50969769-837e1e35a02cf09097b5591db",B="https://pixabay.com/api/";async function m(o,r=1,n=15){return(await v.get(B,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}const M=new O(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery");function h(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:a,comments:P,downloads:q})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img class="gallery-img" src="${n}" alt="${e}" />
        </a>
        <div class="image-info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${P}</p>
          <p><b>Downloads</b> ${q}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function R(){f.innerHTML=""}const y=document.querySelector("#loader");y.style.display="none";function b(){y.style.display="block"}function w(){y.style.display="none"}const g=document.querySelector("#load-more-btn");g.style.display="none";function L(){g.style.display="block"}function c(){g.style.display="none"}const S=document.querySelector(".form"),x=S.elements["search-text"],H=document.querySelector("#load-more-btn");let l=1,u="";const d=15;let p=0;S.addEventListener("submit",async o=>{o.preventDefault();const r=x.value.trim();if(!r){i.warning({message:"Please enter a search term!",position:"topRight"});return}u=r,l=1,R(),b(),c();try{const n=await m(u,l,d);if(p=n.totalHits,n.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}h(n.hits),p>d&&L()}catch(n){console.error(n),i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});H.addEventListener("click",async()=>{l+=1,b(),c();try{const o=await m(u,l,d);h(o.hits),I(),document.querySelectorAll(".gallery-item").length>=p?(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):L()}catch(o){console.error(o),i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});function I(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
